TicketsResale/Controllers/TicketsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketsResale.Business.Models;
using TicketsResale.Models;
using TicketsResale.Models.Service;

namespace TicketsResale.Controllers
{
    public class TicketsController : Controller
    {
        private readonly IStringLocalizer<TicketsController> localizer;
        private readonly ITicketsService ticketsService;
        private readonly IEventsService eventsService;
        private readonly IVenuesService venuesService;
        private readonly ICitiesService citiesService;
        private readonly IUsersAndRolesService usersAndRolesService;
        private readonly IOrdersService ordersService;

        public TicketsController(ITicketsService ticketsService, IEventsService eventsService, IVenuesService venuesService, ICitiesService citiesService, IUsersAndRolesService usersAndRolesService, IOrdersService ordersService, IStringLocalizer<TicketsController> localizer)
        {
            this.localizer = localizer;
            this.ticketsService = ticketsService;
            this.eventsService = eventsService;
            this.venuesService = venuesService;
            this.citiesService = citiesService;
            this.usersAndRolesService = usersAndRolesService;
            this.ordersService = ordersService;
        }

        public async Task<IActionResult> GetEventTickets(int eventId)
        {
            EventTicketsViewModel model;

            Dictionary<Event, List<Ticket>> dic = new Dictionary<Event, List<Ticket>>();

            ViewData["Title"] = localizer["ticketsTitle"];

            var @event = await eventsService.GetEventById(eventId);

            var eventTickets = await ticketsService.GetTicketsByEventId(eventId);
            var eventVenue = await venuesService.GetVenueById(@event.VenueId);
            var eventCity = await citiesService.GetCityById(eventVenue.CityId);

            var sellersIdsByEvent = eventTickets.AsEnumerable().Select(et => et.SellerId).ToList();

            var sellersOfTicketsByEvent = await usersAndRolesService.GetUsersByListOfId(sellersIdsByEvent);

            dic.Add(@event, eventTickets);

            model = new EventTicketsViewModel
            {
                eventTickets = dic,   
                Venue = eventVenue,
                City = eventCity,
                Sellers = sellersOfTicketsByEvent
            };


            return View("EventTickets", model);
        }


        [Authorize]
        public async Task<IActionResult> MyTickets(TicketStatuses ticketStatus, string userName)
        {
            ViewData["Title"] = localizer["myTicketsTitle"];

            var tickets = await ticketsService.GetTicketsByStatusAndUserName(ticketStatus, userName);

            var model = new MyTicketsViewModel
            {
                Tickets = tickets,
                Events = await eventsService.GetEventsByTickets(tickets),
                Users = await usersAndRolesService.GetUsers(),
                ticketStatus = ticketStatus
            };
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Buy([FromRoute] int id)
        {
            var ticket = await ticketsService.GetTicketById(id);

            await ordersService.AddTicketToOrder(User.Identity.Name, ticket);

            ticket.Status = TicketStatuses.waiting;

            await ticketsService.UpdTicketToDb(ticket);

            return RedirectToAction("Index", "Orders", ticket);
        }


        [Authorize]
        public async Task<IActionResult> CreateTicket()
        {
            ViewData["Title"] = localizer["createTicket"];

            var events = await eventsService.GetEvents();

            var listEvents = new SelectList(events, "Id", "Name");

            ViewBag.Events = listEvents;

            return View("CreateTicket");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateTicket(TicketCreateEditModel model)
        {
            var user = await usersAndRolesService.GetUserByUserName(User.Identity.Name);

            var @event = await eventsService.GetEventById(model.Event.Id);

            var venue = await venuesService.GetVenueById(@event.VenueId);

            var city = await citiesService.GetCityById(venue.CityId);

            if (venue != null)
                @event.Venue = venue;

            if (city != null)
                @event.Venue.City = city;

            if (user != null)
                model.Seller = user;

            if (@event != null)
                model.Event = @event;

            Ticket ticket = new Ticket() { EventId = model.Event.Id, Event = model.Event, SellerId = model.Seller.Id, Seller = model.Seller, Price = model.Price, Status = model.Status };

            await ticketsService.AddTicketToDb(ticket);

            return RedirectToAction("MyTickets", new { ticketStatus = 1, userName = User.Identity.Name });

        }


        [Authorize]
        public async Task<IActionResult> ConfirmTicket(int id)
        {
            var ticket = await ticketsService.GetTicketById(id);
            var @event = await eventsService.GetEventById(ticket.EventId);

            if (ticket != null)
            {
                var model = new ConfirmRejectTicketViewModel
                {
                    Ticket = ticket,
                    Event = @event
                };

                return View(model);
            }
           
            return NotFound();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ConfirmTicket(ConfirmRejectTicketViewModel model, int ticketId)
        {
            var needOrders = await ordersService.GetOrdersByTicketId(ticketId);

            var needTicket = await ticketsService.GetTicketById(ticketId);

            foreach (Order order in needOrders)
            {
                order.Status = model.Confirmation ? OrderStatuses.confirmed : OrderStatuses.rejected;
                order.TrackNumber = model.TrackNumber;
                await ordersService.UpdOrderToDb(order);
            }

            if (model.Confirmation)
            {
                needTicket.Status = TicketStatuses.sold;
                await ticketsService.UpdTicketToDb(needTicket);
            }

            return RedirectToAction("MyTickets", new { ticketStatus = 1, orderStatus = 0, userName = User.Identity.Name });

        }

    }
}

TicketsResale/Views/Tickets/ConfirmTicket.cshtml
@model ConfirmRejectTicketViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer


@{
    ViewData["Title"] = "Confirmation of ticket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@localizer["Confirmation of ticket"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ConfirmTicket">
            <div class="form-group">
                <b>@localizer["Name"]</b> <br>
                @Model.Ticket.Event.Name
            </div>
            <div class="form-group">
                <b>@localizer["Price"]</b><br>
                @Model.Ticket.Price
            </div>
            <div class="form-group">
                @localizer["Confirm or reject ticket"] <input style="" asp-for="@Model.Confirmation" class="form-control" />
                <small>@localizer["textReject"]</small>

            </div>
            <div class="form-group">
                <small>@localizer["textReason"]</small>
                <input asp-for="@Model.TrackNumber" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="@localizer["Save"]" class="btn btn-success" asp-route-ticketId="@Model.Ticket.Id" />
                <input type="submit" value="@localizer["Back"]" class="btn btn-primary" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="1" asp-route-userName="@User.Identity.Name" />
            </div>
        </form>
    </div>
</div>

TicketsResale/Views/Tickets/MyTickets.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@model MyTicketsViewModel
<header>
    <div>
        <h1>@localizer["My tickets"]</h1>
    </div>
    <ul class="nav nav-tabs justify-content-center">
        <li class="nav-item bg-dark text-light">
            @if (Model.ticketStatus == TicketsResale.Business.Models.TicketStatuses.selling)
            { <a class="nav-link bg-primary text-light" asp-area="" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="1" asp-route-userName="@User.Identity.Name">@localizer["Selling"]</a>}
            else
            { <a class="nav-link bg-dark text-light" asp-area="" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="1" asp-route-userName="@User.Identity.Name">@localizer["Selling"]</a>}
        </li>
        <li class="nav-item bg-dark text-light">
            @if (Model.ticketStatus == TicketsResale.Business.Models.TicketStatuses.waiting)
            { <a class="nav-link bg-primary text-light" asp-area="" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="2" asp-route-userName="@User.Identity.Name">@localizer["Waiting Confirmation"]</a> }
            else 
            { <a class="nav-link bg-dark text-light" asp-area="" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="2" asp-route-userName="@User.Identity.Name">@localizer["Waiting Confirmation"]</a>}
        </li>
        <li class="nav-item bg-dark text-light">
            @if (Model.ticketStatus == TicketsResale.Business.Models.TicketStatuses.sold)
            {<a class="nav-link bg-primary text-light" asp-area="" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="3" asp-route-userName="@User.Identity.Name">@localizer["Sold"]</a>}
            else
            { <a class="nav-link bg-dark text-light" asp-area="" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="3" asp-route-userName="@User.Identity.Name">@localizer["Sold"]</a>}
        </li>
    </ul>
</header>
<p></p>
<ul class="nav nav-tabs bg-dark">

    <li class="nav-item">
        <a class="nav-link text-light" asp-action="CreateTicket">
            @localizer["Create ticket"]
        </a>
    </li>
</ul>
<table class="table bg-dark text-light">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                @localizer["Name"]
            </th>
            <th>
                @localizer["Date"]
            </th>
            <th>
                @localizer["Price"]
            </th>
            <th>
                @localizer["Seller"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ticket in Model.Tickets)
        {
            <tr>
                <td>
                    <img src="~/img/ticket.jpg" alt="Ticket" class="card-img-top" />
                </td>
                <td>
                    @Model.Events.Where(e => e.Id == ticket.EventId).Select(e => e.Name).FirstOrDefault()
                </td>
                <td>
                    @ticket.Event.Date.Date.ToShortDateString()
                </td>
                <td>
                    $@ticket.Price
                </td>
                <td>
                    @Model.Users.Where(u => u.Id == ticket.SellerId.ToString()).Select(u => u.FirstName).FirstOrDefault() @Model.Users.Where(u => u.Id == ticket.SellerId.ToString()).Select(u => u.LastName).FirstOrDefault()
                </td>
                @if (Model.ticketStatus == TicketsResale.Business.Models.TicketStatuses.waiting)
                {
                    <td>
                        <ul class="nav flex-column bg-dark">
                            <li class="nav-item bg-primary">
                                <a class="nav-link text-light" asp-action="ConfirmTicket" asp-controller="Tickets" asp-route-id="@ticket.Id">
                                    @localizer["Confirm"] | @localizer["Reject"]
                                </a>
                            </li>
                        </ul>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

TicketsResale/Views/Tickets/TicketCreateEdit.cshtml
@model TicketsResale.Models.TicketCreateEditModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTicket">
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label asp-for="Event" class="control-label"></label>
                <select asp-for="@Model.Event.Id" class="form-control" asp-items="@ViewBag.Events"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="submit" value="Back" class="btn btn-primary" asp-controller="Tickets" asp-action="MyTickets" asp-route-ticketStatus="1" asp-route-userName="@User.Identity.Name"/>
            </div>
        </form>
    </div>
</div>