TicketsResale/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System.Threading.Tasks;
using TicketsResale.Models;
using TicketsResale.Models.Service;

namespace TicketsResale.Business.Models
{
    public class EventsController : Controller
    {
        private readonly IStringLocalizer<EventsController> localizer;
        private readonly IEventsService eventsService;
        private readonly IVenuesService venuesService;
        private readonly ICitiesService citiesService;

        public EventsController(IStringLocalizer<EventsController> localizer, IEventsService eventsService, IVenuesService venuesService, ICitiesService citiesService)
        {

            this.localizer = localizer;
            this.eventsService = eventsService;
            this.venuesService = venuesService;
            this.citiesService = citiesService;
        }
        public async Task<IActionResult> Index()  
        {
            ViewData["Title"] = localizer["eventstitle"];

            var model = new EventsViewModel
            {
                EventsCategories = await eventsService.GetEventsCategories(),
                Cities = await citiesService.GetCities()
            };

            return View(model);
        }
    }
}

TicketsResale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
    <title>@ViewData["Title"] - TicketsResale</title>
    <script src="~/dist/site.entry.js" type="module" defer></script>
    <link rel="stylesheet" href="~/dist/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/icons/ticket-shop-light.svg" width="40" height="40" class="d-inline-block align-top" alt="" loading="lazy"> TicketsResale
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">

                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/img/icons/home-light.svg" width="20" height="20" class="d-inline-block align-top" alt="" loading="lazy"> @localizer["Home"]
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Events" asp-action="Index">
                                <!-- asp-route-categoryId="1" -->
                                <img src="~/img/icons/events-light.svg" width="20" height="20" class="d-inline-block align-top" alt="" loading="lazy"> @localizer["Events"]
                            </a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row row-cols-2">
                <div class="col-lg-6">
                    &copy; 2020 - A.Karmilchik - TicketsResale - <a asp-area="" asp-controller="Home" asp-action="Privacy">@localizer["Privacy"]</a>
                </div>
                <div class="col-lg-6">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        @Html.ActionLink(localizer["EN"].Value, "SetLanguage", "Language", new { locale = "en-US", @returnUrl = @Context.Request.Path.Value.ToString() }, new { @class = "btn btn-dark", @type = "button"} )
                        @Html.ActionLink(localizer["RU"].Value, "SetLanguage", "Language", new { locale = "ru-RU", @returnUrl = @Context.Request.Path.Value.ToString() }, new { @class = "btn btn-dark", @type = "button" })
                        @Html.ActionLink(localizer["BY"].Value, "SetLanguage", "Language", new { locale = "be-BY", @returnUrl = @Context.Request.Path.Value.ToString() }, new { @class = "btn btn-dark", @type = "button" })
                    </div>
                </div>
            </div>
        </div>    
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>